# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weidongurls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('environment', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=1000)),
                ('business', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('comment', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='weidongusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('portrait', models.CharField(max_length=300)),
                ('environment', models.CharField(max_length=40)),
                ('flag', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('belongtourl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vincent.weidongurls')),
            ],
        ),
    ]
